### PR TITLE
Fix global variable hoisting

### LINKED ISSUE #42: Reachability is incorrect for assignments
Currently when reassigning a function name, its access graphs appear to be correct but the reachability is not computed correctly.

```
function foo() { }

renamed = foo;

function bar() {
    renamed();
}
```

In the above example, `foo` should be reachable from `bar`, but it is not.

There is already a test in vuln-reach which is currently ignored:
```
javascript::lang::accesses::tests::renamed_function
```

### PR DESCRIPTION
**Pull request by cd-work**
This fixes an issue where assignments without declaration wouldn't be correctly considered to be part of the global scope, despite JavaScript hoisting any assignment without declaration by default.

In theory the hoisting only happens when an assignment is executed, so the following code alone is not sufficient to define the global `test`:

```js
function foo() {
    test = 5;
}
```

However any code executing this function `foo` will permanently hoist `test` to be a global variable. With our current symbol table representation, the only viable way to map this is to assume `test` is always a variable assigned in the global `program` scope.

This hoisting behavior can be suppressed retroactively by declaring the variable using the `var` keyword. Retroactive declaration does not work with `let` or `const`. This is why finding the globally hoisted variables requires finding any potential `var` declarations in the current scope first.

Closes #42.

### CODE REVIEW

File: vuln-reach/src/javascript/lang/symbol_table.rs [hunk 1]
```diff
@@ -158,6 +180,16 @@ impl<'a> SymbolTableBuilder<'a> {
 
                 self.visit_children(node);
             },
+            "assignment_expression" | "augmented_assignment_expression" => {
+                // Add assignments to their scope, allowing identification of hoisted variables.
+                let scope = self.find_parent_function_scope().unwrap();
+                let name = node.child_by_field_name(b"left").unwrap();
+                if !scope.names.contains(&name) {
```
Comment (cd-work) [inline vuln-reach/src/javascript/lang/symbol_table.rs:187]: This is a tiny optimization which should help with all well behaved JavaScript code.

So the only cases where things will be added is if it's either going to be hoisted, or if the declaration is after the assignment. Realistically both of these are something I'd consider poor JavaScript, so hopefully performance shouldn't be hit too badly.

File: vuln-reach/src/javascript/lang/symbol_table.rs [hunk 2]
```diff
@@ -59,7 +62,21 @@ impl<'a> SymbolTableBuilder<'a> {
...
-        SymbolTable { tree, scopes: visitor.scope_table, scope_indices }
+        let mut table = SymbolTable { tree, scopes: visitor.scope_table, scope_indices };
+
+        // Hoist assignments which were not declared as variables.
+        for i in 0..table.scopes.len() {
+            let assignments = mem::take(&mut table.scopes[i].assignments);
+            for name in assignments {
+                let cursor = Cursor::new(tree, name).unwrap();
+                if table.lookup(cursor).is_none() {
+                    println!("HOISTING {:?}", name);
```
Comment (andreaphylum) [inline vuln-reach/src/javascript/lang/symbol_table.rs:73]: This was probably meant for debugging only?

File: vuln-reach/src/javascript/lang/symbol_table.rs (hunk 1 above)
Comment (andreaphylum) [reply vuln-reach/src/javascript/lang/symbol_table.rs:187]: Even if it was relatively common, I honestly think this is completely fine as it is.

**Review by andreaphylum — CHANGES_REQUESTED** [review]
Looks good. I greatly prefer the recursive evaluation of accessors to the previous precedence based system.

**Review by andreaphylum — APPROVED** [review]
